name: moneyTI CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'centos:latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Copy secret
        env:
          GCP_SECRET: ${{ secrets.GCP_CREDENTIALS }}
          GCP_SECRET_DIR: src/main/resources
          GCP_SECRET_DIR_FILE_NAME: gcp-credentials.json
        run: echo $GCP_SECRET | base64 --decode > $GCP_SECRET_DIR/$GCP_SECRET_DIR_FILE_NAME

      - name: Set environment properties
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION }}" >> ./application.yml
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build

      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/moneyti .
          docker push ${{ secrets.DOCKER_USERNAME }}/moneyti:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          #          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            docker stop $(docker ps -a -q) 
            docker rm $(docker ps -a -q) 
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/moneyti:latest
            sudo docker tag ${{ secrets.DOCKER_USERNAME }}/moneyti:latest moneyti
            sudo docker-compose up -d